package: insightapplications
distribution: prospective
release: vcs
component: main
version: 3.20.0
source: insightapplications
homepage: http://itk.org/ITK/resources/applications.html
license: BSD
blend: debian-med
descr:
- package: insightapplications
  description: InsightToolKit (ITK) based medical imaging applications
  long_description: " A variety of applications providing segmentation, registration,
    and\n other medical image processing algorithms such as MRI bias field\n correction."
  release: vcs
  license: BSD
  blend: debian-med
