about:
  home: https://github.com/bcgsc/mavis_config.git
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: Config validation for running MAVIS via Snakemake
build:
  noarch: python
  number: 0
  run_exports:
  - None
  script: -m pip install . -vvv --no-deps --no-build-isolation --use-pep517
package:
  name: mavis-config
  version: 1.2.2
requirements:
  host:
  - python >=3.7
  - pip
  run:
  - python >=3.7
  - snakemake-minimal >=7.18.1
  - braceexpand
source:
  sha256: b44e24d8b0ef2d406cdbc3e6c82bb6e6d26d1056d80c10bc5deda8b2b223a9e5
  url: https://pypi.io/packages/source/m/mavis-config/mavis_config-1.2.2.tar.gz
test:
  imports:
  - mavis_config
