about:
  description: "#### Tools - ExtractTsv\n\nThis mean can extract samples, libraries\
    \ and readgroups from a sample config file. This meant as a supporting tool inside\
    \ wdl pipelines.\nIt can also output a single layer as tsv file.\n\n\n#### Tools\
    \ - ReadFromTsv\n\nThis tool enables a user to create a full sample sheet in JSON\
    \ format or\nYAML format, suitable for all Biopet Queue pipelines, from TSV file(s).\n\
    \n\n#### Tools - CromwellArrays\n\nThis tool will convert the sample configs to\
    \ a array based format that can be used inside wdl pipelines.\nThis tool is only\
    \ to support biowdl pipelines.\n\n\n#### Tools - CaseControl\n\n This tool will\
    \ extract the case-control pairs from a sample config file.\n It will read the\
    \ headers of the bam files to confirm that samples do exist.\n\nFor documentation\
    \ and manuals visit our github.io page: https://biopet.github.io/sampleconfig\n"
  home: https://github.com/biopet/sampleconfig
  license: MIT
  summary: '#### Tools - ExtractTsv  This mean can extract samples, libraries and
    readgroups from a sample config file.'
build:
  noarch: generic
  number: 1
extra:
  notes: 'biopet-sampleconfig is a Java program that comes with a custom wrapper shell
    script.

    By default ''no default java option'' is set in the wrapper.

    The command that runs the program is ''biopet-sampleconfig''.

    If you want to overwrite it you can specify memory options directly after your
    binaries.

    If you have _JAVA_OPTIONS set globally this will take precedence.

    For example run it with ''biopet-sampleconfig -Xms512m -Xmx1g''.

    '
package:
  name: biopet-sampleconfig
  version: '0.3'
requirements:
  run:
  - openjdk >=8,<9
  - python
source:
  sha256: f14655c26e5208a82d6a27fedef77b8961bc47eb3b9fdaa61ba67d60b282af7f
  url: https://github.com/biopet/sampleconfig/releases/download/v0.3/SampleConfig-assembly-0.3.jar
test:
  commands:
  - biopet-sampleconfig ExtractTsv --version
  - biopet-sampleconfig ExtractTsv --help
  - biopet-sampleconfig ReadFromTsv --version
  - biopet-sampleconfig ReadFromTsv --help
  - biopet-sampleconfig CromwellArrays --version
  - biopet-sampleconfig CromwellArrays --help
