about:
  home: http://metacpan.org/pod/AppConfig
  license: perl_5
  summary: AppConfig is a bundle of Perl5 modules for reading configuration files
    and parsing command line arguments.
build:
  noarch: generic
  number: 2
package:
  name: perl-appconfig
  version: '1.71'
requirements:
  build:
  - make
  host:
  - perl
  - perl-test-pod
  run:
  - perl
source:
  md5: 7747d9241561ed5567d5e134b8648707
  url: https://cpan.metacpan.org/authors/id/N/NE/NEILB/AppConfig-1.71.tar.gz
test:
  imports:
  - AppConfig
  - AppConfig::Args
  - AppConfig::CGI
  - AppConfig::File
  - AppConfig::Getopt
  - AppConfig::State
  - AppConfig::Sys
