about:
  home: http://gtk2-perl.sourceforge.net
  license: unknown
  summary: simplistic interface to pkg-config
build:
  noarch: generic
  number: 2
package:
  name: perl-extutils-pkgconfig
  version: '1.16'
requirements:
  build:
  - make
  host:
  - perl
  - perl-extutils-makemaker
  - pkg-config
  run:
  - perl
source:
  sha256: bbeaced995d7d8d10cfc51a3a5a66da41ceb2bc04fedcab50e10e6300e801c6e
  url: https://cpan.metacpan.org/authors/id/X/XA/XAOC/ExtUtils-PkgConfig-1.16.tar.gz
test:
  imports:
  - ExtUtils::PkgConfig
