name: Run gh2biotools if biotools.json files changed

on:
  push:
    branches:
      - 'develop'
    paths:
      - 'data/**/**/*.biotools.json'

jobs:
  run-gh2biotools:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          sparse-checkout: 'data'
          sparse-checkout-cone-mode: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'


      - name: Check if commit author is NOT biotools-bot
        id: check_author
        run: |
          AUTHOR_NAME="${{ github.actor }}"
          echo "Commit author: $AUTHOR_NAME"
          if [ "${{ github.actor }}" = "biotools-bot" ]; then
            echo "allowed=false" >> $GITHUB_OUTPUT
            echo "No action needed. Commit made by biotools-bot."
            exit 0
          else
            echo "allowed=true" >> $GITHUB_OUTPUT
          fi


      - name: diff
        run: |
          echo "Changed files:"
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }}

      - name: Check if any .biotools.json files were changed
        id: check_changes
        run: |
          files=$(git diff-tree --no-commit-id --name-only --diff-filter=d -r ${{ github.sha }} | grep '\.biotools\.json$' || true)

          if [ -z "$files" ]; then
            echo "No relevant biotools.json files changed."
            echo "changed=false" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Files changed:"
            echo "$files"
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "files=${files}" >> $GITHUB_OUTPUT
          fi


      - name: Get list of deleted files
        id: deleted_files
        run: |
          deleted_files=$(git diff-tree --no-commit-id --name-only --diff-filter D -r ${{ github.sha }} | grep '\.biotools\.json$' || true)

          if [[ -n "$deleted_files" ]]; then
            echo "deleted=true" >> $GITHUB_OUTPUT
            echo "Deleted files: $deleted_files"
            echo "deleted_files=${deleted_files}" >> $GITHUB_OUTPUT
          else
            echo "deleted=false" >> $GITHUB_OUTPUT
            echo "No files were deleted in this commit."
          fi

      - name: Checkout utils repo
        uses: actions/checkout@v3
        with:
          repository: anitamnd/research-software-ecosystem-utils
          path: content-ecosystem-utils


      - name: Install dependencies
        working-directory: content-ecosystem-utils/scripts/runbiotools
        run: |
          pip3 install -r requirements.txt


      - name: Run gh2biotools.py script
        if: steps.check_author.outputs.allowed == 'true' && (steps.check_changes.outputs.changed == 'true' || steps.deleted_files.outputs.deleted == 'true')
        env:
          BIOTOOLS_API_TOKEN: ${{ secrets.BIOTOOLS_API_TOKEN }}
        run: |
          changed_files="${{ steps.check_changes.outputs.files }}"
          deleted_files="${{ steps.deleted_files.outputs.deleted_files }}"

          command="python content-ecosystem-utils/scripts/runbiotools/gh2biotools2.py --token \"$BIOTOOLS_API_TOKEN\""

          if [[ -n "$changed_files" ]]; then
            command="$command --files \"$changed_files\""
          fi

          if [[ -n "$deleted_files" ]]; then
            command="$command --deleted \"$deleted_files\""
          fi

          echo "Running command: $command"
          eval "$command"
